### ISSUE TITLE
Keep getting Null reference exception on a simple request call

### ISSUE THREAD

**Issue by mohammad-shadmehr** [KeyserDSoze/Rystem.OpenAi#71] opened 2023-12-05 07:10 UTC
### Describe the bug

I have already set the openai in the start up via dependency injection. I am just trying to make a simple request but keep getting a null reference exception. I can see the _iOpenAi is not null and have no idea if I am missing something in my code?

### To Reproduce

just a simple request call

### Code snippets

```ASP.NET
public class ChatGptManager : IChatGptManager
    {
        private readonly IOpenAi _iOpenAi;

        public ChatGptManager(IOpenAi iOpenAi)
        {
            _iOpenAi = iOpenAi;
        }
        public async Task<string> Generate(List<string> input)
        {

            var result = await _iOpenAi.Chat
                .Request(new ChatMessage { Role = ChatRole.User, Content = "Hi there" })
                .WithModel(ChatModelType.Gpt35Turbo)
                .WithTemperature(1)
                .ExecuteAsync();


            return result.ToString();
        }
    }
```

### OS

Windows

### .Net version

.Net 7

### Library version

1.0.3

**Comment by Kuubs** [comment] 2023-12-05 07:49
I get the same. Even when using the Rystem.OpenAi.WebApp from this repo. 
My only changes: 
`var apiKey = builder.Configuration["OpenAi:ApiKey"];
builder.Services.AddOpenAi(settings =>
{
    settings.ApiKey = apiKey;
});`

**Comment by mohammad-shadmehr** [comment] 2023-12-05 08:56
here is mine in the Startup.cs:
services.AddOpenAi(settings =>
            {
                settings.ApiKey = _appConfiguration["Chat-Gpt:SecretKey"];
            });

**Comment by bartoandras** [comment] 2023-12-14 18:42
Getting the same error. When will it be fixed?

**Comment by williamcajina** [comment] 2024-01-19 03:01
Also getting this erro

**Comment by taylorchasewhite** [comment] 2024-01-27 13:29
This is a duplicate of #70.

**Comment by taylorchasewhite** [comment] 2024-04-05 00:44
@KeyserDSoze any idea if this (#70 has the technical details) has been addressed? I see there have been a few releases recently, I can do another upgrade and test out if you are unsure.

**Comment by KeyserDSoze** [comment] 2024-12-14 00:42
New version solved this issue.

**Closed by KeyserDSoze** 2024-12-14 00:42 UTC
Labels: bug
